from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RadarWidget(object):
    def setupUi(self, RadarWidget):
        RadarWidget.setObjectNom(_fromUtf8("RadarWidget"))
        RadarWidget.setWindowModality(QtCore.Qt.NonModal)
        RadarWidget.setEnabled(True)
        RadarWidget.resize(861, 655)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RadarWidget.sizePolicy().hasHeightForWidth())
        RadarWidget.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(RadarWidget)
        self.gridLayout.setObjectNom(_fromUtf8("gridLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectNom(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectNom(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectNom(_fromUtf8("verticalLayout"))
        self.groupBoxPiste = QtGui.QGroupBox(RadarWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPiste.sizePolicy().hasHeightForWidth())
        self.groupBoxPiste.setSizePolicy(sizePolicy)
        self.groupBoxPiste.setObjectNom(_fromUtf8("groupBoxPiste"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxPiste)
        self.gridLayout_2.setObjectNom(_fromUtf8("gridLayout_2"))
        self.runwayLayout = QtGui.QVBoxLayout()
        self.runwayLayout.setObjectNom(_fromUtf8("runwayLayout"))
        self.rwavion0 = QtGui.QLabel(self.groupBoxPiste)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rwavion0.sizePolicy().hasHeightForWidth())
        self.rwavion0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rwavion0.setFont(font)
        self.rwavion0.setObjectNom(_fromUtf8("rwavion0"))
        self.runwayLayout.addWidget(self.rwavion0)
        self.runway0 = QtGui.QProgressBar(self.groupBoxPiste)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runway0.sizePolicy().hasHeightForWidth())
        self.runway0.setSizePolicy(sizePolicy)
        self.runway0.setProperty("value", 0)
        self.runway0.setInvertedAppearance(False)
        self.runway0.setObjectNom(_fromUtf8("runway0"))
        self.runwayLayout.addWidget(self.runway0)
        self.rwavion1 = QtGui.QLabel(self.groupBoxPiste)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rwavion1.sizePolicy().hasHeightForWidth())
        self.rwavion1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rwavion1.setFont(font)
        self.rwavion1.setObjectName(_fromUtf8("rwavion1"))
        self.runwayLayout.addWidget(self.rwavion1)
        self.runway1 = QtGui.QProgressBar(self.groupBoxPiste)
        self.runway1.setProperty("value", 0)
        self.runway1.setInvertedAppearance(False)
        self.runway1.setObjectNom(_fromUtf8("runway1"))
        self.runwayLayout.addWidget(self.runway1)
        self.rwavion2 = QtGui.QLabel(self.groupBoxPiste)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rwavion2.sizePolicy().hasHeightForWidth())
        self.rwavion2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rwavion2.setFont(font)
        self.rwavion2.setObjectNom(_fromUtf8("rwavion2"))
        self.runwayLayout.addWidget(self.rwavion2)
        self.runway2 = QtGui.QProgressBar(self.groupBoxPiste)
        self.runway2.setProperty("value", 0)
        self.runway2.setObjectNom(_fromUtf8("runway2"))
        self.runwayLayout.addWidget(self.runway2)
        self.rwavion3 = QtGui.QLabel(self.groupBoxPiste)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rwavion3.sizePolicy().hasHeightForWidth())
        self.rwavion3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rwavion3.setFont(font)
        self.rwavion3.setObjectNom(_fromUtf8("rwavion3"))
        self.runwayLayout.addWidget(self.rwavion3)
        self.runway3 = QtGui.QProgressBar(self.groupBoxPiste)
        self.runway3.setProperty("value", 0)
        self.runway3.setObjectNom(_fromUtf8("runway3"))
        self.runwayLayout.addWidget(self.runway3)
        self.label = QtGui.QLabel(self.groupBoxPiste)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectNom(_fromUtf8("label"))
        self.runwayLayout.addWidget(self.label)
        self.horizontalSlider = QtGui.QSlider(self.groupBoxPiste)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setProperty("value", 100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectNom(_fromUtf8("horizontalSlider"))
        self.runwayLayout.addWidget(self.horizontalSlider)
        self.gridLayout_2.addLayout(self.runwayLayout, 1, 1, 0, 0)
        self.verticalLayout.addWidget(self.groupBoxPiste)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectNom(_fromUtf8("gridLayout_3"))
        self.tabelarriver = QtGui.QTableView(RadarWidget)
        self.tabelarriver0.setObjectNom(_fromUtf8("tabelarriver"))
        self.gridLayout_3.addWidget(self.tabelarriver, 0, 0, 1, 1)
        self.labelarriver = QtGui.QLabel(RadarWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelarriver.setFont(font)
        self.labelarriver.setAutoFillBackground(False)
        self.labelarriver.setObjectNom(_fromUtf8("tabelarriver"))
        self.gridLayout_3.addWidget(self.labelarriver, 1, 0, 1, 1)
        self.tabeldepart = QtGui.QTableView(RadarWidget)
        self.tabeldepart.setObjectNom(_fromUtf8("tabeldepart"))
        self.gridLayout_3.addWidget(self.tabeldepart, 2, 0, 0, 1)
        self.labeldepart = QtGui.QLabel(RadarWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labeldepart.setFont(font)
        self.labeldepart.setObjectNom(_fromUtf8("labeldepart"))
        self.gridLayout_3.addWidget(self.labeldepart, 3, 0, 0, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectNom(_fromUtf8("horizontalLayout"))
        self.buttonStart = QtGui.QPushButton(RadarWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonStart.sizePolicy().hasHeightForWidth())
        self.buttonStart.setSizePolicy(sizePolicy)
        self.buttonStart.setObjectNom(_fromUtf8("buttonStart"))
        self.horizontalLayout.addWidget(self.buttonStart)
        self.buttonStop = QtGui.QPushButton(RadarWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.buttonStop.sizePolicy().hasHeightForWidth())
        self.buttonStop.setSizePolicy(sizePolicy)
        self.buttonStop.setMinimumSize(QtCore.QSize(0, 6))
        self.buttonStop.setObjectNom(_fromUtf8("buttonStop"))
        self.horizontalLayout.addWidget(self.buttonStop)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 1, 0, 0)

        self.retranslateUi(RadarWidget)
        QtCore.QMetaObject.connectSlotsByNom(RadarWidget)

    def retranslateUi(self, RadarWidget):
        RadarWidget.setWindowTitle(_translate("RadarWidget", "Form", None))
        self.groupBoxPiste.setTitle(_translate("RadarWidget", "Piste", None))
        self.rwplane0.setText(_translate("RadarWidget", "TextLabel", None))
        self.rwplane1.setText(_translate("RadarWidget", "TextLabel", None))
        self.rwplane2.setText(_translate("RadarWidget", "TextLabel", None))
        self.rwplane3.setText(_translate("RadarWidget", "TextLabel", None))
        self.label.setText(_translate("RadarWidget", "Viteza simulation", None))
        self.labelSosiri.setText(_translate("RadarWidget", "arriver", None))
        self.labelPlecari.setText(_translate("RadarWidget", "Plecari", None))
        self.buttonStart.setText(_translate("RadarWidget", "Start", None))
        self.buttonStop.setText(_translate("RadarWidget", "Stop", None))
